version: "3.7"
services:
  php:
    restart: always
    tty: true
    image: z4riix/php8-alpine
    volumes:
      - ./laravel:/var/www/html # plz check your laravel project path
    command: /usr/sbin/php-fpm8 -F
  composer:
    image: z4riix/composer
    volumes:
      - ./laravel:/app
    depends_on:
      - php
  nginx:
    restart: always
    image: z4riix/nginx
    volumes:
      - ./laravel:/var/www/html
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8888:80"
    depends_on:
      - php
  node:
    image: z4riix/node
    volumes:
      - ./laravel:/app # plz check your laravel project path
    command: npm install
    depends_on:
      - php
  adminer:
    image: z4riix/adminer
    restart: always
    ports:
      - "8080:8080"
    command: /usr/bin/php8 -S 0.0.0.0:8080 -t /var/www/html
  postgres:
    image: z4riix/postgres
    restart: always
    environment:
      POSTGRES_USER: laravel 
      POSTGRES_PASSWORD: laravel
      POSTGRES_DB: laravel
    ports:
      - "5432:5432"